//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPortfolioDBEntities : DbContext
    {
        public MyPortfolioDBEntities()
            : base("name=MyPortfolioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAbouts> TblAbouts { get; set; }
        public virtual DbSet<TblAboutsCards> TblAboutsCards { get; set; }
        public virtual DbSet<TblAdmins> TblAdmins { get; set; }
        public virtual DbSet<TblCertificates> TblCertificates { get; set; }
        public virtual DbSet<TblExpertiseCards> TblExpertiseCards { get; set; }
        public virtual DbSet<TblExpertiseItems> TblExpertiseItems { get; set; }
        public virtual DbSet<TblFirst> TblFirst { get; set; }
        public virtual DbSet<TblMessages> TblMessages { get; set; }
        public virtual DbSet<TblSocialMedia> TblSocialMedia { get; set; }
        public virtual DbSet<TblProjects> TblProjects { get; set; }
        public virtual DbSet<TblProjectTechnologies> TblProjectTechnologies { get; set; }
        public virtual DbSet<TblInformation> TblInformation { get; set; }
    }
}
