//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAboutsCards
    {
        public byte Id { get; set; }
        public string CardIcon { get; set; }
        public string CardBaslik { get; set; }
        public string CardAltBaslik { get; set; }
        public string CardAltBaslik2 { get; set; }
    }
}
