//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCertificates
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Institution { get; set; }
        public string Date { get; set; }
        public string CertificateLink { get; set; }
        public string Icon { get; set; }
    }
}
