//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExpertiseItems
    {
        public int Id { get; set; }
        public int ExpertiseCardId { get; set; }
        public string IconClass { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual TblExpertiseCards TblExpertiseCards { get; set; }
    }
}
