//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFirst
    {
        public byte Id { get; set; }
        public string WebsiteTitle { get; set; }
        public string NavTitle { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Subtitle2 { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string CvUrl { get; set; }
    }
}
