//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProjectTechnologies
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string TechnologyName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual TblProjects TblProjects { get; set; }
    }
}
